In [2]:
1+1

2

# Introduction

In [3]:
False or True

True

In [4]:
True or False and True

True

In [8]:
lst=['1',2,3]

In [10]:
lst.append([8,9])

##  List- Append, Extend and Insert

In [11]:
lst

['1', 2, 3, [8, 9]]

In [12]:
lst.extend([6,7,3])

In [13]:
lst

['1', 2, 3, [8, 9], 6, 7, 3]

In [14]:
lst.insert(2,'4')

In [15]:
lst

['1', 2, '4', 3, [8, 9], 6, 7, 3]

## Pop, Count and Index

In [18]:
lst.pop()

3

In [19]:
lst.pop(4)

[8, 9]

In [20]:
lst

['1', 2, '4', 3, 6, 7]

In [24]:
lst.count(2) #count number of elements in the list

1

In [25]:
lst.index(3) #it will give the index of the value/elemet

3

In [26]:
lst.index(2,1,5) # here 1,5 is the start and end index - range you want to search

1

## Set

In [34]:
set_va=set()
set_va={'f','s','w'}

In [35]:
set_va

{'f', 's', 'w'}

In [36]:
type(set_va)

set

In [42]:
set1={2,3,5,6,4,9}

In [43]:
set2={3,5,6,7}

In [39]:
set2.difference(set1) #this will give the set2-set1 element

{7}

In [40]:
set2.difference_update(set1) # update will change the element value 

In [41]:
set2

{7}

In [44]:
set2

{3, 5, 6, 7}

In [45]:
set2.intersection(set1) # this will give common between set1 and set 2 set1 U set2

{3, 5, 6}

In [46]:
set2.intersection_update(set1)

In [47]:
set2

{3, 5, 6}

## Dictionaries

In [48]:
#key value pair

In [1]:
my_dict={'Ca1':'abc','cae':'asa','123':'cac'}

In [3]:
my_dict['cae']

'asa'

In [4]:
#Nested Dictory

car_dict={'Ca1':{'avs':'vas'},'cae':'asa','123':'cac'}

In [9]:
print(car_dict['Ca1']['avs'])

vas


## Tuples

In [10]:
#Cannot change element in tuples

In [11]:
tuple_temp=('vatsal','abc','jas')

In [13]:
tuple_temp.index('abc')

1

In [17]:
tuple_temp.count('vatsal')

1

# Numpy

In [22]:
#Array which can store value of same data stype

import numpy as np

In [26]:
my_lst=[1,2,3]
arr=np.array(my_lst)

In [28]:
my_lst[2]

3

In [29]:
type(arr)

numpy.ndarray

In [44]:
my_lst=[[1,2,3],[2,4,5],[5,6,3]] # this will be consider as list 

 
arr1=np.array(my_lst) #Always use this to convert to array

In [50]:
arr1

array([[1, 2, 3],
       [2, 4, 5],
       [5, 6, 3]])

In [47]:
arr1.shape

(3, 3)

In [55]:
arr1.reshape(1,9) # always in reshape the total number of elements

array([[1, 2, 3, 2, 4, 5, 5, 6, 3]])

## Indexing

In [59]:
arr1.reshape(3,3)

array([[1, 2, 3],
       [2, 4, 5],
       [5, 6, 3]])

In [62]:
arr1[:,2:]

array([[3],
       [5],
       [3]])

In [65]:

# Arage


arr=np.arange(1,9,step=3) 

In [66]:
arr

array([1, 4, 7])

In [67]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [68]:
# Copy function

arr1

array([[1, 2, 3],
       [2, 4, 5],
       [5, 6, 3]])

In [69]:
arr[2:]=100

In [70]:
arr

array([  1,   4, 100])

In [ ]:
#Copy, random, 

In [71]:
# To avoid the reference type on the array copy() function can be used

In [72]:
arr

array([  1,   4, 100])

In [73]:
arr1

array([[1, 2, 3],
       [2, 4, 5],
       [5, 6, 3]])

In [75]:
arr2=arr # this will be cause reference type

arr2=arr1.copy() # this will be value type- means it will store in different memory space

In [76]:
arr2

array([[1, 2, 3],
       [2, 4, 5],
       [5, 6, 3]])

In [77]:
arr2*2

array([[ 2,  4,  6],
       [ 4,  8, 10],
       [10, 12,  6]])

In [79]:
#random distribution

np.random.rand(3,2)

array([[0.60251705, 0.4073623 ],
       [0.61414609, 0.54275153],
       [0.63225462, 0.67926344]])

In [80]:
arr1*arr2

array([[ 1,  4,  9],
       [ 4, 16, 25],
       [25, 36,  9]])

In [81]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [82]:
np.random.rand(3,3)

array([[0.09170298, 0.67878099, 0.17445993],
       [0.36803339, 0.51123887, 0.66709604],
       [0.56022647, 0.20235127, 0.42790463]])

# Pandas

In [2]:
import pandas as pd

In [115]:
 df=pd.DataFrame(np.arange(0,20).reshape(4,5),index=['Row1','2','3','4'],columns=['Col1','Col2','Col1','Col3','Col1'],dtype=int)

In [116]:
df

Col1  Col2  Col1  Col3  Col1
Row1     0     1     2     3     4
2        5     6     7     8     9
3       10    11    12    13    14
4       15    16    17    18    19

In [96]:
#Accessing the elements
# 1 .loc
# 2. iloc

In [98]:
type(df.loc['2'])

pandas.core.series.Series

In [99]:
df.loc['2']  # this will be values

Col1    5
Col2    6
Col1    7
Col2    8
Col1    9
Name: 2, dtype: int32

In [101]:
df.iloc[2,3] # this will work on index

13

In [102]:
# Convert dataframe to array


df.iloc[:,1:].values

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [107]:
df.isnull().sum()

Col1    0
Col2    0
Col1    0
Col2    0
Col1    0
dtype: int64

In [110]:
df

Col1  Col2  Col1  Col2  Col1
Row1     0     1     2     3     4
2        5     6     7     8     9
3       10    11    12    13    14
4       15    16    17    18    19

In [117]:
df['Col3'].value_counts()

13    1
3     1
18    1
8     1
Name: Col3, dtype: int64

In [118]:
df=pd.read_csv('mercedesbenz.csv')

In [120]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [122]:
df.info

<bound method DataFrame.info of         ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X

In [123]:
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [124]:
df.corr()

ID         y       X10  X11       X12       X13       X14  \
ID    1.000000 -0.055108  0.001602  NaN  0.058988 -0.031917 -0.025438   
y    -0.055108  1.000000 -0.026985  NaN  0.089792  0.048276  0.193643   
X10   0.001602 -0.026985  1.000000  NaN -0.033084 -0.028806 -0.100474   
X11        NaN       NaN       NaN  NaN       NaN       NaN       NaN   
X12   0.058988  0.089792 -0.033084  NaN  1.000000  0.214825 -0.246513   
...        ...       ...       ...  ...       ...       ...       ...   
X380 -0.013577  0.040932 -0.010479  NaN -0.005566  0.023045  0.007743   
X382 -0.038171 -0.159815 -0.010164  NaN -0.024937 -0.021713  0.012713   
X383 -0.009332  0.040291 -0.004740  NaN -0.011628 -0.010125  0.023604   
X384 -0.015355 -0.004591 -0.002532  NaN -0.006212  0.041242  0.025199   
X385  0.029059 -0.022280 -0.004387  NaN -0.010765 -0.009373  0.043667   

           X15       X16       X17  ...      X375      X376      X377  \
ID    0.002237 -0.036480 -0.038171  ...  0.045229 -0.080259 -0.022965   
y     0.023116  0.048946 -0.159815  ...  0.029100  0.114005  0.061403   
X10  -0.002532 -0.005944 -0.010164  ...  0.165277 -0.028618 -0.074244   
X11        NaN       NaN       NaN  ...       NaN       NaN       NaN   
X12  -0.006212 -0.014584 -0.024937  ... -0.107864 -0.070214  0.030134   
...        ...       ...       ...  ...       ...       ...       ...   
X380 -0.001968 -0.004619 -0.007899  ... -0.061741 -0.022240 -0.061168   
X382 -0.001908 -0.004480  1.000000  ... -0.059883 -0.021571 -0.059327   
X383 -0.000890 -0.002089 -0.003572  ... -0.015413 -0.010059  0.035107   
X384 -0.000475 -0.001116 -0.001908  ... -0.014917 -0.005373  0.008694   
X385 -0.000824 -0.001934 -0.003307  ...  0.055225 -0.009311 -0.025610   

          X378      X379      X380      X382      X383      X384      X385  
ID    0.030371  0.023382 -0.013577 -0.038171 -0.009332 -0.015355  0.029059  
y    -0.258679  0.067919  0.040932 -0.159815  0.040291 -0.004591 -0.022280  
X10  -0.016870 -0.011374 -0.010479 -0.010164 -0.004740 -0.002532 -0.004387  
X11        NaN       NaN       NaN       NaN       NaN       NaN       NaN  
X12  -0.016043 -0.027907 -0.005566 -0.024937 -0.011628 -0.006212 -0.010765  
...        ...       ...       ...       ...       ...       ...       ...  
X380 -0.013110 -0.008839  1.000000 -0.007899 -0.003683 -0.001968 -0.003410  
X382 -0.012716 -0.008573 -0.007899  1.000000 -0.003572 -0.001908 -0.003307  
X383 -0.005930 -0.003998 -0.003683 -0.003572  1.000000 -0.000890 -0.001542  
X384 -0.003168 -0.002136 -0.001968 -0.001908 -0.000890  1.000000 -0.000824  
X385 -0.005489 -0.003701 -0.003410 -0.003307 -0.001542 -0.000824  1.000000  

[370 rows x 370 columns]

# CSV

In [125]:
from io import StringIO, BytesIO

In [135]:
data = ('col1,col2,c3\n'
            'x,y,1\n'
            'a,b,2\n'
            'c,d,3')

In [136]:
type(data)

str

In [137]:

pd.read_csv(StringIO(data))

col1 col2  c3
0    x    y   1
1    a    b   2
2    c    d   3

In [142]:
df=pd.read_csv(StringIO(data), usecols=['col1', 'c3'])

In [143]:
df

col1  c3
0    x   1
1    a   2
2    c   3

In [144]:
df.to_csv('test.csv')

In [145]:
# you can change the index in dataframe

data = ('index,a,b,c\n'
           '4,apple,bat,5.7\n'
            '8,orange,cow,10')

In [146]:
data

'index,a,b,c\n4,apple,bat,5.7\n8,orange,cow,10'

In [148]:

pd.read_csv(StringIO(data))

index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [149]:

pd.read_csv(StringIO(data),index_col=0)

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [152]:
 # this can be use if its take column as index 
pd.read_csv(StringIO(data),index_col=False)

index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [153]:
 data = ('a,b,c\n'
           '4,apple,bat,\n'
            '8,orange,cow,')

In [154]:
pd.read_csv(StringIO(data))

a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [155]:
pd.read_csv(StringIO(data),index_col=False)

a       b    c
0  4   apple  bat
1  8  orange  cow

In [156]:
pd.read_csv(StringIO(data),index_col=False)

a       b    c
0  4   apple  bat
1  8  orange  cow

In [172]:
## Quoting and Escape characters 

data=('1,2,3\n'
         'w,d,f\n'
     'w,d,f\n')

In [174]:
pd.read_csv(StringIO(data))

1  2  3
0  w  d  f
1  w  d  f

In [184]:
data= ('a,b\n'
        'hello \\''bob\\'',nice to see you",5')

In [185]:
pd.read_csv(StringIO(data),escapechar='\\')

a  b
0  hello bob,nice to see you"  5

In [9]:
## URL to CSV

df=pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',sep='\t') #this will access the data from the URL

HTTPError: HTTP Error 403: Forbidden

## Read Json, HTML to CSV


In [7]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'


Data1= '{"employe":"james", "emao":"fjd@gmai", "dfask": [{"asd":"asa","asda":"asa"}]}'

pd.read_json(Data)

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [8]:
df1= pd.read_json(Data1)

In [9]:
df1

employe      emao                          dfask
0   james  fjd@gmai  {'asd': 'asa', 'asda': 'asa'}

In [10]:
df1.to_json()

'{"employe":{"0":"james"},"emao":{"0":"fjd@gmai"},"dfask":{"0":{"asd":"asa","asda":"asa"}}}'

In [14]:
df1.to_json(orient='records')

'[{"employe":"james","emao":"fjd@gmai","dfask":{"asd":"asa","asda":"asa"}}]'

In [21]:
## Reading html to csv

url='https://www.fdic.gov/bank/individual/failed/banklist.html'


In [1]:
import pandas as pd

In [5]:
url = 'https://www.fdic.gov/bank/individual/failed/banklist.html'



In [7]:
url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
dfs = pd.read_html(url_mcc, match='Country', header=0)

In [8]:
dfs[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

## Pickling

In [11]:
dfs[0].to_pickle('dfs_temp')

In [16]:
df1=pd.read_pickle('dfs_temp')

In [17]:
df1.head()

Mobile country code                                    Country ISO 3166  \
0                  289                                 A Abkhazia    GE-AB   
1                  412                                Afghanistan       AF   
2                  276                                    Albania       AL   
3                  603                                    Algeria       DZ   
4                  544  American Samoa (United States of America)       AS   

                             Mobile network codes National MNC authority  \
0        List of mobile network codes in Abkhazia                    NaN   
1     List of mobile network codes in Afghanistan                    NaN   
2         List of mobile network codes in Albania                    NaN   
3         List of mobile network codes in Algeria                    NaN   
4  List of mobile network codes in American Samoa                    NaN   

                    Remarks  
0  MCC is not listed by ITU  
1                       NaN  
2                       NaN  
3                       NaN  
4                       NaN